# This image runs the dcos-cli test suite.

FROM ubuntu:16.04
MAINTAINER support@mesosphere.com

RUN apt-get update && apt-get install -y \
  httpie \
  jq \
  make \
  python3-venv \
  openssh-client \
  git \
  sudo \
  python3-pip \
&& python3 -m pip install pyinstaller==3.1.1

ADD . /dcos-cli
WORKDIR /dcos-cli
RUN make clean env packages

WORKDIR /dcos-cli/cli
RUN make clean env packages

RUN make binary && PATH=/dcos-cli/cli/dist:$PATH
